config/routes.rb
LostTie::Application.routes.draw do
  root :to => "home#index"

  match "/contact" => redirect("/contact-us")

  resources :portfolio, :only => :index
  match '/portfolio' => 'portfolio#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contact_us/contacts/new.html.erb
<h2><%= t('.contact_us') %></h2>
<%= form_for @contact, :url => contacts_path, :html => {:class => 'formtastic'} do |f| %>
  <% if ContactUs.require_name %>
    <li class='string required' id='contact_us_contact_name_input'>
      <%= f.label :name, (t('.name') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :name %>
      <% if f.object.errors[:name].present? %>
        <p class='inline-error'><%= f.object.errors[:name].join(' and ') %></p>
      <% end %>
    </li>
  <% end %>
  <li class='string required' id='contact_us_contact_email_input'>
    <%= f.label :email, (t('.email') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_field :email %>
    <% if f.object.errors[:email].present? %>
      <p class='inline-error'><%= f.object.errors[:email].join(' and ') %></p>
    <% end %>
  </li>
  <% if ContactUs.require_subject %>
    <li class='string required' id='contact_us_contact_subject_input'>
      <%= f.label :subject, (t('.subject') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :subject %>
      <% if f.object.errors[:subject].present? %>
        <p class='inline-error'><%= f.object.errors[:subject].join(' and ') %></p>
      <% end %>
    </li>
  <% end %>
  <li class='text required' id='contact_us_contact_message_input'>
    <%= f.label :message, (t('.message') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_area :message %>
    <% if f.object.errors[:message].present? %>
      <p class='inline-error'><%= f.object.errors[:message].join(' and ') %></p>
    <% end %>
  </li>
  <li class='commit'>
    <%= f.submit :submit, :alt => t('.submit'), :class => 'submit create', :label => t('.submit'), :title => t('.submit') %>
  </li>
<% end %>

app/views/contact_us/contacts/new_formtastic.html.erb
<h2><%= t('.contact_us') %></h2>
<%= semantic_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.action :submit, :label => t('.submit'), :button_html => { :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') } %>
<% end %>

app/views/contact_us/contacts/new_simple_form.html.erb
<div class="row">
  <div class="large-9 columns">

    <h3>We'd love to hear from you!</h3>
    <p>
      Drop us a line or shoot over an email. You can even contact a team member with a specific question. We're excited to hear about your project!
    </p>
    <h5 class="title" style="left: 199px;">
      <a href="#panel2">The Team</a>
    </h5>
    <div class="content" data-slug="panel2" style="">
      <ul class="large-block-grid-5">
        <li>
          <a href="mailto:contact@losttie.com">
            Jason Rylance
          </a>
          <p>Director, Lead Developer<br>
          361-288-4278</p>
        </li>
        <li>
          <a href="mailto:contact@losttie.com">
            Andrew Foster
          </a>
          <p>Graphic Design, Marketing<br>
          210-422-2054</p>
        </li>
        <li>
          <a href="mailto:contact@losttie.com">
            Eric Whittley
          </a>
          <p>User Experience, Lead Technical<br>
          512-588-2452</p>
        </li>
        <li>
          <a href="mailto:contact@losttie.com">
            Fabian Puente
          </a>
          <p>Graphic Design<br>
          512-789-4653</p>
        </li>
      </ul>
    </div>
    <div class="content" data-slug="panel1" style="">
      <%= simple_form_for @contact, :url =>
      contacts_path do |f| %>
      <div class="row collapse">
        <div class="large-2 columns">
          <label class="inline">Name</label>
        </div>
        <div class="large-10 columns">
          <%= f.input :name, :label =>false, :placeholder => 'Jane Doe' %>
        </div>
      </div>
      <div class="row collapse">
        <div class="large-2 columns">
          <label class="inline">Email</label>
        </div>
        <div class="large-10 columns">
          <%= f.input :email, :label =>false, :placeholder => 'jane@doeco.com' %>
        </div>
      </div>
      <div class="row collapse">
        <div class="large-2 columns">
          <label class="inline">Company</label>
        </div>
        <div class="large-10 columns">
          <%= f.input :subject, :label =>false, :placeholder => 'Doe Co' %>
        </div>
      </div>
      <div class="row collapse">
        <div class="large-2 columns">
          <label class="inline">Message</label>
        </div>
        <div class="large-10 columns">
          <%= f.input :message, :as =>
          :text, :label => false, :placeholder => 'I want to build a neat website!' %>
        </div>
      </div>
      <button type="submit" class="radius button">Send</button>
      <% end %>
    </div>
  </div>
  <div class="large-3 columns">
    <h5>Phone or Email</h5>
    <p>
      361-288-4278
      <br>
      <a href="mailto:contact@losttie.com">contact@losttie.com</a>
    </p>
  </div>
</div>

app/views/home/_slider.html.erb
<div id="sequence-theme">
    <div id="sequence">
        <ul class="sequence-canvas">
            <li class="animate-in">
                <div class="intro">
                    <h2>A website can help your business earn you money</h2>
                    <h3></h3>
                </div>
                <img class="floating" src="/assets/images/floating.png" alt="floating" />
                <img class="floating-shadow" src="/assets/images/floating-shadow.png" />
            </li>
            <li>
                <img class="ipad" src="/assets/images/ipad.png" alt="iPad" />
                <div class="slide2">
                    <h2>A one time investment can yield an ongoing ROI.</h2>
                    <p>Sliders using CSS3 transitions</p>
                </div>
                <img class="ipad-shadow" src="/assets/images/ipad-shadow.png" />
            </li>
            <li>
                <div class="slide3">
                    <h2>Cutting Edge</h2>
                    <p>The edge has not been cut!</p>
                </div>
                <img class="iphone2" src="/assets/images/iphone.png" alt="iPhone4" />
                <img class="iphone2-shadow" src="/assets/images/iphone-shadow.png" />
                <img class="iphone3" src="/assets/images/iphone.png" alt="iPhone4" />
                <img class="iphone3-shadow" src="/assets/images/iphone-shadow.png" />
                <img class="iphone4" src="/assets/images/iphone.png" alt="iPhone4" />
                <img class="iphone4-shadow" src="/assets/images/iphone-shadow.png" />
            </li>
        </ul>
    </div>
</div>

app/views/home/index.html.erb
<div class="row">

  <div class="large-6 columns text-center">
    <%= image_tag "floating.png", :alt=>"floating alien mascot" %></div>

  <div class="large-6 columns marginalize-top">
    <h3 class="show-for-small">We create solutions for lost websites</h3>
    <h4 class="hide-for-small">We create solutions for lost websites</h4>
    <h5 class="subheader">
      A website should help market your business and bring in new revenue. Let us take care of the hard stuff and help maximize the return on your website.
    </h5>
    <br>
    <h3 class="show-for-small">Offering Service in Corpus Christi</h3>
    <h4 class="hide-for-small">Offering Service in Corpus Christi</h4>
    <h5 class="subheader">
      Our primary area of operation is in Corpus Christi, TX.  As such, we typically work with clients from the surrounding areas - if you are outside of town don't hesitate to call and see if we can find a solution for your area.
    </h5>
  </div>

</div>
<hr>
<div class="row">

  <div class="hide-for-small large-6 columns text-right marginalize-top">
    <h3 class="show-for-small">
      We offer web development services that make your business better
    </h3>
    <h4 class="hide-for-small">
      We offer web development services that make your business better
    </h4>
    <h5 class="subheader">
      An effective website turns a visitor into a customer. By understanding the
      <span>science</span>
      behind this we can create custom designed websites which make your business stand out.
    </h5>
  </div>

  <div class="large-6 columns text-center">
    <%= image_tag "standing.png", :alt=>"standing alien mascot" %></div>

  <div class="show-for-small large-6 columns">
    <h3 class="show-for-small">
      We offer web development services that make your business better.
    </h3>
    <h4 class="hide-for-small">
      We offer web development services that make your business better.
    </h4>
    <h5 class="subheader">
      An effective website turns a visitor into a customer. By understanding the
      <span>science</span>
      behind this we can create custom designed websites which make your business stand out.
    </h5>
  </div>

</div>
<hr>
<div class="row" id="services">
  <div class="large-6 columns">
    <div class="text-center">
      <%= image_tag "home_page/shopping_cart.png", :alt=>
      "shopping cart" %>
      <h4 class="show-for-small">Create New Shopping Experiences</h4>
      <h4 class="hide-for-small">Create New Shopping Experiences</h4>
    </div>
    <p class="subheader text-center">
      Online stores are a great way to expand your business.  Not only can we get your store online, we can create a marketing tactic that will yield predictable sales.
    </p>
  </div>
  <div class="large-6 columns">
    <div class="text-center">
      <%= image_tag "home_page/custom_software.png", :alt=>
      "customized software" %>
      <h4 class="show-for-small">Forge Customized Tools For Your Business</h4>
      <h4 class="hide-for-small">Forge Customized Tools For Your Business</h4>
    </div>
    <p class="subheader text-center">
      We build web applications that are specially-made to meet the needs of your business. Need to allow your customers to set up appointments? Want to track monthly quotas and performance? We've got this covered.
    </p>
  </div>
</div>

<div class="row">
  <div class="large-6 columns">
    <div class="text-center">
      <%= image_tag "home_page/virtual_business_card.png", :alt=>
      "virtual business card" %>
      <h4 class="show-for-small">Set Up Quick Profiles</h4>
      <h4 class="hide-for-small">Set Up Quick Profiles</h4>
    </div>
    <p class="subheader text-center">
      Maybe you just need something simple. We can set up single page profiles that convey what you do without the cost of a large-scale website.
    </p>
  </div>
  <div class="large-6 columns">
    <div class="text-center">
      <%= image_tag "home_page/event_broadcaster.png", :alt=>
      "microphone" %>
      <h4 class="show-for-small">Broadcast Your Event</h4>
      <h4 class="hide-for-small">Broadcast Your Event</h4>
    </div>
    <p class="subheader text-center">
      You have a one-time event, and it's coming up quick. We can provide a more rapid turnaround time for these situations.
    </p>
  </div>

</div>

app/views/layouts/_footer.html.erb
<div class="large-12 columns">
  <hr>
  <div class="row">
    <div class="large-5 columns">
      <p>Lost Tie LLC Call Jason: 361-288-4278</p>
    </div>
    <div class="large-7 columns">
      <ul class="inline-list right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Services", root_path(:anchor => "services") %>
        <li><%= link_to "Portolio", portfolio_path %></li>
        <li><%= link_to "Contact", contact_us_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="nav-container contain-to-grid">
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <%= link_to image_tag("logo.png", :alt=>"logo"), root_path, :class => 'logo' %></li>
      <li class="toggle-topbar menu-icon">
        <a href="#">
          <span><text class="show-for-medium">Menu</text></span>
        </a>
      </li>
    </ul>

    <section class="top-bar-section">
      <!-- Left Nav Section -->

      <!-- Right Nav Section -->
      <ul class="right">
        <li>
          <%= link_to "Home", root_path, :class =>('active' if current_page?root_path) %></a>
        </li>
        <li>
          <%= link_to "Portfolio", portfolio_path, :class =>('active' if current_page?portfolio_path) %>
        </li>
        <li>
          <%= link_to "Contact", contact_us_path, :class =>('active' if current_page?contact_us_path) %></a>
        </li>
      </ul>
    </section>
  </nav>
  <hr class="hide-for-small">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Lost Tie Web Development" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Professional web development for Corpus Christi, TX." %>
  ">
  <%= stylesheet_link_tag "application", :media =>
  "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
  <%= favicon_link_tag 'favicon.png' %>
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31605971-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  </script>
  </head>
<body class="<%= controller_name %>
  <%= action_name %>
  ">
  <div id="container" class="container">
    <header>
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/messages' %></header>
    <div id="main" role="main">
      <%= yield %>
    </div>
    <footer class="row">
      <%= render 'layouts/footer' %></footer>
  </div>
  <!--! end of #container -->
</body>
</html>

app/views/portfolio/index.html.erb
<div class="row">
  <div class="12 columns text-center">
    <h1>Getting Online</h1>
  </div>
  <div class="large-6 columns text-center">
    <%= link_to (image_tag "dannysincometax.png", :alt=>
    "Danny's Income Tax"), "http://dannystaxprep.com/" %>
    <br>
  </div>

  <div class="large-6 columns">
    <h3 class="show-for-small">Background</h3>
    <h4 class="hide-for-small">Background</h4>
    <h5 class="subheader">
      Danny's Income Tax Service had been a successful tax preperation business for over a decade, but never made a committment to a professionally designed website.
    </h5>
    <h3 class="show-for-small">Results</h3>
    <h4 class="hide-for-small">Results</h4>
    <h5 class="subheader">
      In the tax season following the launch of the website, revenues were up over 17% from the previous year.
    </h5>
    <h5 class="subheader">
      In addition to having a more apparent presence when new clients are searching online for tax preparation services, Danny is looking to market his IRS resolution services nation-wide with a future website expansion.
    </h5>
  </div>

</div>
<hr>

<div class="row">
  <div class="12 columns text-center">
    <h1>Communicating With Guests</h1>
  </div>
  <div class="hide-for-small large-6 columns">
    <h3 class="show-for-small">Background</h3>
    <h4 class="hide-for-small">Background</h4>
    <h5 class="subheader">
      The Bleu Bistro aquired a new lead chef and was looking to communicate their new menu to their guests.
    </h5>
    <h3 class="show-for-small">Results</h3>
    <h4 class="hide-for-small">Results</h4>
    <h5 class="subheader">
      With an attractive layout that matched the ambiance of the restaurant itself, the Bleu Bistro was able to display its new menu with detailed pictures of all of their dishes.
    </h5>
    <h5 class="subheader">
      The management is also able to update their website to communicate changes and events using an interface that is as simple as checking your email.
    </h5>
  </div>

  <div class="large-6 columns text-center">
    <%= link_to (image_tag "bleubistro.png", :alt=>
    "Bleu Bistro"), "http://bleubistrocc.com/" %>
    <br>
  </div>

  <div class="show-for-small large-6 columns">
    <h3 class="show-for-small">Background</h3>
    <h4 class="hide-for-small">Background</h4>
    <h5 class="subheader">
      The Bleu Bistro aquired a new lead chef and was looking to communicate their new menu to their previous guests.
    </h5>
    <h3 class="show-for-small">Results</h3>
    <h4 class="hide-for-small">Results</h4>
    <h5 class="subheader">
      With an attractive layout that matched the ambiance of the restaurant itself, the Bleu Bistro was able to display its new menu with detailed pictures of all of their dishes.
    </h5>
    <h5 class="subheader">
      The management is also able to update their website to communicate changes and events using an interface that is as simple as checking your email.
    </h5>
  </div>

</div>
<hr>

<div class="row">
  <div class="12 columns text-center">
    <h1>A Hobby Turned Business</h1>
  </div>
  <div class="large-6 columns text-center">
    <%= link_to (image_tag "angelwood.png", :alt=>
    "AngelWood of South Texas"), "http://angelwoodofsouthtexas.com/" %>
    <br>
  </div>
  <div class="large-6 columns">
    <h3 class="show-for-small">Background</h3>
    <h4 class="hide-for-small">Background</h4>
    <h5 class="subheader">
      Harry Angel enjoys bringing out the natural beauty of wood.  His skill at sculpting mesquite drew enough attention to realize he could make a business of his hobby.  After successfully sculpting and selling face-to-face for a number of years, he and his wife decided it was time to enhance their online presence.
    </h5>
    <h3 class="show-for-small">Results</h3>
    <h4 class="hide-for-small">Results</h4>
    <h5 class="subheader">
      We designed an online store that matched the aesthetics of the sculptures themselves.  Angel Wood of South Texas, Harry's company, can now use the website as a tool to enhance the visibility of past work while being able to sell new work.
    </h5>
    <h5 class="subheader">
      The website is not only funcitonal as a storefront, it is a full featured marketing tool.  From the search terms guests used to get there, to how many items a guests added to their basket, the ability to track various data allows Angel Wood to plan any future online marketing techniques appropriately and efficiently.
    </h5>
  </div>

</div>
<hr>

<div class="row">
  <div class="12 columns text-center">
    <h1>Custom Built Software to Make a Job Easier</h1>
  </div>
  <div class="hide-for-small large-6 columns">
    <h3 class="show-for-small">Background</h3>
    <h4 class="hide-for-small">Background</h4>
    <h5 class="subheader">
      A branch of the Diocese of Corpus Christi, the St. Paul School of Catechism, needed a simpler way of managing their private school's paperwork.
    </h5>
    <h3 class="show-for-small">Results</h3>
    <h4 class="hide-for-small">Results</h4>
    <h5 class="subheader">
      We built a customized application that allows teachers to record grades and attendance for their students without physical paperwork that would have to be passed on to the school's administration recordkeeping.
    </h5>
    <h5 class="subheader">
      The administration can spend less time worrying about where paperwork is and more time actually managing the education program.
    </h5>
  </div>

  <div class="large-6 columns text-center">
    <%= image_tag "spsc.png", :alt=>
    "St. Paul School of Catechism" %>
    <br>
  </div>

  <div class="show-for-small large-6 columns">
    <h3 class="show-for-small">Background</h3>
    <h4 class="hide-for-small">Background</h4>
    <h5 class="subheader">
      A branch of the Diocese of Corpus Christi, the St. Paul School of Catechism, needed a simpler way of managing their private school's paperwork.
    </h5>
    <h3 class="show-for-small">Results</h3>
    <h4 class="hide-for-small">Results</h4>
    <h5 class="subheader">
      We built a customized application that allows teachers to record grades and attendance for their students without physical paperwork that would have to be passed on to the school's administration recordkeeping.
    </h5>
    <h5 class="subheader">
      The administration can spend less time worrying about where paperwork is and more time actually managing the education program.
    </h5>
  </div>

</div>
<hr>

<div class="row">
  <div class="12 columns text-center">
    <h1>We Even Do Redesigns</h1>
  </div>
  <div class="large-6 columns text-center">
    <%= image_tag "cleandesign.png", :alt=>
    "Clean Design" %>
    <br>
  </div>

  <div class="large-6 columns">
    <h3 class="show-for-small">Background</h3>
    <h4 class="hide-for-small">Background</h4>
    <h5 class="subheader">
      A great example of this is with Lost Tie's own previous website.  We were bored with the design and wanted to change things around.
    </h5>
    <h3 class="show-for-small">Results</h3>
    <h4 class="hide-for-small">Results</h4>
    <h5 class="subheader">
      We updated our design to more clearly reflect our company's culture.  We wanted our website to be an extension of how we operate behind the scenes: clean, organized, and not distracted by outside noise.
    </h5>
    <h5 class="subheader">
      Not only the looks of the website have changed, but the technology powering it has changed.  Our company moved focus toward developing Ruby on Rails applications instead of ASP.NET applications. . .  so we wanted the website to move along with us.
    </h5>
  </div>

</div>